namespace BiteDanceAPI.Domain.Constants;

public static class LocationConst
{
    // https://thuvienphapluat.vn/chinh-sach-phap-luat-moi/vn/ho-tro-phap-luat/tu-van-phap-luat/55568/danh-sach-63-tinh-thanh-cua-viet-nam-theo-vung-mien
    public static readonly string[] CityAllowList =
    [
        "TP.Hồ Chí Minh",
        "Hà Nội",
        "An Giang",
        "Bà Rịa - Vũng Tàu",
        "Bình Dương",
        "Bình Phước",
        "Bình Thuận",
        "Bình Định",
        "Bạc Liêu",
        "Bắc Giang",
        "Bắc Kạn",
        "Bắc Ninh",
        "Bến Tre",
        "Cao Bằng",
        "Cà Mau",
        "Cần Thơ",
        "Điện Biên",
        "Đà Nẵng",
        "Đắk Lắk",
        "Đắk Nông",
        "Đồng Nai",
        "Đồng Tháp",
        "Gia Lai",
        "Hoà Bình",
        "Hà Giang",
        "Hà Nam",
        "Hà Tĩnh",
        "Hưng Yên",
        "Hải Dương",
        "Hải Phòng",
        "Hậu Giang",
        "Khánh Hoà",
        "Kiên Giang",
        "Kon Tum",
        "Lai Châu",
        "Long An",
        "Lào Cai",
        "Lâm Đồng",
        "Lạng Sơn",
        "Nam Định",
        "Nghệ An",
        "Ninh Bình",
        "Ninh Thuận",
        "Phú Thọ",
        "Phú Yên",
        "Quảng Bình",
        "Quảng Nam",
        "Quảng Ngãi",
        "Quảng Ninh",
        "Quảng Trị",
        "Sóc Trăng",
        "Sơn La",
        "Thanh Hoá",
        "Thái Bình",
        "Thái Nguyên",
        "Thừa Thiên Huế",
        "Tiền Giang",
        "Trà Vinh",
        "Tuyên Quang",
        "Tây Ninh",
        "Vĩnh Long",
        "Vĩnh Phúc",
        "Yên Bái",
    ];
    public static readonly string[] CountryAllowList = ["Viet Nam"];
}
